# Generated by Django 3.2.4 on 2021-06-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(upload_to='media/images')),
                ('status', models.BooleanField(blank=True)),
            ],
        )
    ]
