# Generated by Django 3.2.4 on 2021-06-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_detector', '0002_auto_20210607_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
