# Generated by Django 3.2.4 on 2021-06-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_detector', '0003_alter_test_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='result_img',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='test',
            name='label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
