# Generated by Django 3.2.4 on 2021-06-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_detector', '0004_auto_20210620_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
